############
## Frames ##
############
base_frame: 'base_link'

###################
## DH-Parameters ##
###################
joints:
  - d: 0.1215
    theta: 0.0
    a: 0.0
    alpha: 1.5708
  - d: 0.1405
    theta: 1.5708
    a: 0.408
    alpha: -3.1416
  - d: 0.1215
    theta: 0.0
    a: 0.376
    alpha: 3.1416
  - d: 0.1025
    theta: 1.5708
    a: 0.0
    alpha: 1.5708
  - d: 0.1025
    theta: 0.0
    a: 0.0
    alpha: -1.5708
  - d: 0.094
    theta: 3.1416
    a: 0.0
    alpha: 0.0


# A1
#  1  0  0  0
#  0  1  0  0
#  0  0  1  0.1215
#  0  0  0  1

# A2
#  0 -1  0  0
#  0  0 -1 -0.1405
#  1  0  0  0
#  0  0  0  1

# A3
#  1  0  0  0.408
#  0 -1  0  0
#  0  0 -1 -0.1215
#  0  0  0  1

# A4
#  0 -1  0  0
# -1  0  0  0
#  0  0 -1 -0.1025
#  0  0  0  1

# A5
#  1  0  0  0
#  0  0 -1 -0.1025
#  0  1  0  0
#  0  0  0  1

# A6
# -1  0  0  0
#  0  0  1  0.094
#  0  1  0  0
#  0  0  0  1
