rmp_motion_controller:
    type: "position_controllers/RMPMotionController"
    base_frame: "panda_link0"
    eef_frame: "panda_link8"
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    links:
      - panda_link1
      - panda_link2
      - panda_link3
      - panda_link4
      - panda_link5
      - panda_link6
      - panda_link7
      - panda_link8
