################################
## Riemannian Motion Policies ##
################################

panda_link1:
  - [0,0,0]

panda_link2:
  - [0,0,0]

panda_link3:
  - [0,0,0]
  - [0,0,-0.2]
  - [0,0,-0.4]

panda_link4:
  - [0,0,0]

panda_link5: 
  - [0,0,0]
  - [0,0,-0.2]
  - [0,0,-0.4]

panda_link6:
  - [0,0,0]

panda_link7:
  - [0,0,0]

panda_link8:
  - [0,0,0]